pipeline {
    agent any

    tools {
        jdk "JDK17"
        maven "Maven3"
        nodejs "Node18"
    }

    stages {

        stage("Checkout") {
            steps {
                checkout scm
            }
        }

        stage("Build Backend") {
            steps {
                dir("RevWorkforce") {
                    bat "mvn clean package -DskipTests"
                }
            }
        }

        stage("Build Frontend") {
            steps {
                dir("RevWorkForce-Frontend") {
                    bat "npm install"
                    bat "npm run build"
                }
            }
        }

        stage("Deploy Backend to EC2") {
            steps {
                echo "Deployment stage"
            }
        }
    }
}
